# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Cueno  
email: mike@q-no.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://q-no.com" # the base hostname & protocol for your site
github_username: michaelcueno

# Build settings
markdown: kramdown

exclude:   
  - bread/node_modules
